export const zendata = [
  {
    q: 'Your heart is the size of an ocean. Go find yourself in its hidden depths.',
    a: 'Rumi',
    c: '74',
    h: '<blockquote>&ldquo;Your heart is the size of an ocean. Go find yourself in its hidden depths.&rdquo; &mdash; <footer>Rumi</footer></blockquote>',
  },
  {
    q: "It's not how much we give but how much love we put into giving.",
    a: 'Mother Teresa',
    c: '63',
    h: "<blockquote>&ldquo;It's not how much we give but how much love we put into giving.&rdquo; &mdash; <footer>Mother Teresa</footer></blockquote>",
  },
  {
    q: 'He who hesitates is a damned fool.',
    a: 'Mae West',
    c: '34',
    h: '<blockquote>&ldquo;He who hesitates is a damned fool.&rdquo; &mdash; <footer>Mae West</footer></blockquote>',
  },
  {
    q: 'The mind can calculate, but the spirit yearns, and the heart wants what the heart wants.',
    a: 'Stephen King',
    c: '88',
    h: '<blockquote>&ldquo;The mind can calculate, but the spirit yearns, and the heart wants what the heart wants.&rdquo; &mdash; <footer>Stephen King</footer></blockquote>',
  },
  {
    q: 'There are no constraints on the human mind, no walls around the human spirit, no barriers to our progress except those we ourselves erect.',
    a: 'Ronald Reagan',
    c: '138',
    h: '<blockquote>&ldquo;There are no constraints on the human mind, no walls around the human spirit, no barriers to our progress except those we ourselves erect.&rdquo; &mdash; <footer>Ronald Reagan</footer></blockquote>',
  },
  {
    q: 'A clear conscience never fears midnight knocking.',
    a: 'Chinese Proverb',
    c: '49',
    h: '<blockquote>&ldquo;A clear conscience never fears midnight knocking.&rdquo; &mdash; <footer>Chinese Proverb</footer></blockquote>',
  },
  {
    q: "If you're waiting until you feel talented enough to make it, you'll never make it.",
    a: 'Criss Jami',
    c: '82',
    h: "<blockquote>&ldquo;If you're waiting until you feel talented enough to make it, you'll never make it.&rdquo; &mdash; <footer>Criss Jami</footer></blockquote>",
  },
  {
    q: 'Never give up work. Work gives you meaning and purpose and life is empty without it.',
    a: 'Stephen Hawking',
    c: '84',
    h: '<blockquote>&ldquo;Never give up work. Work gives you meaning and purpose and life is empty without it.&rdquo; &mdash; <footer>Stephen Hawking</footer></blockquote>',
  },
  {
    q: "It's beautiful to be alone. To be alone does not mean to be lonely. It means the mind is not influenced and contaminated by society.",
    a: 'Jiddu Krishnamurti',
    c: '132',
    h: "<blockquote>&ldquo;It's beautiful to be alone. To be alone does not mean to be lonely. It means the mind is not influenced and contaminated by society.&rdquo; &mdash; <footer>Jiddu Krishnamurti</footer></blockquote>",
  },
  {
    q: 'It is truth that liberates, not your effort to be free.',
    a: 'Jiddu Krishnamurti',
    c: '55',
    h: '<blockquote>&ldquo;It is truth that liberates, not your effort to be free.&rdquo; &mdash; <footer>Jiddu Krishnamurti</footer></blockquote>',
  },
  {
    q: 'The best fighter is never angry.',
    a: 'Lao Tzu',
    c: '32',
    h: '<blockquote>&ldquo;The best fighter is never angry.&rdquo; &mdash; <footer>Lao Tzu</footer></blockquote>',
  },
  {
    q: 'One of the really tough things is figuring out what questions to ask. Once you figure out the question, then the answer is relatively easy.',
    a: 'Elon Musk',
    c: '139',
    h: '<blockquote>&ldquo;One of the really tough things is figuring out what questions to ask. Once you figure out the question, then the answer is relatively easy.&rdquo; &mdash; <footer>Elon Musk</footer></blockquote>',
  },
  {
    q: 'Educating the mind without educating the heart is no education at all.',
    a: 'Aristotle',
    c: '70',
    h: '<blockquote>&ldquo;Educating the mind without educating the heart is no education at all.&rdquo; &mdash; <footer>Aristotle</footer></blockquote>',
  },
  {
    q: 'Do not look for a sanctuary in anyone except your self.',
    a: 'Buddha',
    c: '55',
    h: '<blockquote>&ldquo;Do not look for a sanctuary in anyone except your self.&rdquo; &mdash; <footer>Buddha</footer></blockquote>',
  },
  {
    q: "Half the world is composed of people who have something to say and can't, and the other half who have nothing to say and keep on saying it.",
    a: 'Robert Frost',
    c: '139',
    h: "<blockquote>&ldquo;Half the world is composed of people who have something to say and can't, and the other half who have nothing to say and keep on saying it.&rdquo; &mdash; <footer>Robert Frost</footer></blockquote>",
  },
  {
    q: 'Do not wait for leaders; do it alone, person to person.',
    a: 'Mother Teresa',
    c: '55',
    h: '<blockquote>&ldquo;Do not wait for leaders; do it alone, person to person.&rdquo; &mdash; <footer>Mother Teresa</footer></blockquote>',
  },
  {
    q: 'Whatever you decide to do, make sure it makes you happy.',
    a: 'Paulo Coelho',
    c: '56',
    h: '<blockquote>&ldquo;Whatever you decide to do, make sure it makes you happy.&rdquo; &mdash; <footer>Paulo Coelho</footer></blockquote>',
  },
  {
    q: 'Know your gifts and share them.',
    a: 'Les Brown',
    c: '31',
    h: '<blockquote>&ldquo;Know your gifts and share them.&rdquo; &mdash; <footer>Les Brown</footer></blockquote>',
  },
  {
    q: 'A man with outward courage dares to die: a man with inner courage dares to live.',
    a: 'Lao Tzu',
    c: '80',
    h: '<blockquote>&ldquo;A man with outward courage dares to die: a man with inner courage dares to live.&rdquo; &mdash; <footer>Lao Tzu</footer></blockquote>',
  },
  {
    q: "Don't blame others. it won't make you a better person.",
    a: 'Lolly Daskal',
    c: '54',
    h: "<blockquote>&ldquo;Don't blame others. it won't make you a better person.&rdquo; &mdash; <footer>Lolly Daskal</footer></blockquote>",
  },
  {
    q: 'Constantly think about how you could be doing things better.',
    a: 'Elon Musk',
    c: '60',
    h: '<blockquote>&ldquo;Constantly think about how you could be doing things better.&rdquo; &mdash; <footer>Elon Musk</footer></blockquote>',
  },
  {
    q: "Becoming a great leader doesn't mean being perfect. it means living with your imperfections.",
    a: 'Lolly Daskal',
    c: '92',
    h: "<blockquote>&ldquo;Becoming a great leader doesn't mean being perfect. it means living with your imperfections.&rdquo; &mdash; <footer>Lolly Daskal</footer></blockquote>",
  },
  {
    q: 'Eighty percent of success is showing up. ',
    a: 'Woody Allen',
    c: '41',
    h: '<blockquote>&ldquo;Eighty percent of success is showing up. &rdquo; &mdash; <footer>Woody Allen</footer></blockquote>',
  },
  {
    q: 'In youth we run into difficulties. In old age difficulties run into us. ',
    a: 'Beverly Sills',
    c: '72',
    h: '<blockquote>&ldquo;In youth we run into difficulties. In old age difficulties run into us. &rdquo; &mdash; <footer>Beverly Sills</footer></blockquote>',
  },
  {
    q: "Don't seek, don't avoid, don't expect. Take what comes and be happy.",
    a: 'Maxime Lagace',
    c: '68',
    h: "<blockquote>&ldquo;Don't seek, don't avoid, don't expect. Take what comes and be happy.&rdquo; &mdash; <footer>Maxime Lagace</footer></blockquote>",
  },
  {
    q: "You play the hand you're dealt. I think the game's worthwhile.  ",
    a: 'Christopher Reeve',
    c: '64',
    h: "<blockquote>&ldquo;You play the hand you're dealt. I think the game's worthwhile.  &rdquo; &mdash; <footer>Christopher Reeve</footer></blockquote>",
  },
  {
    q: 'Beware of false knowledge, it is more dangerous than ignorance.',
    a: 'George Bernard Shaw',
    c: '63',
    h: '<blockquote>&ldquo;Beware of false knowledge, it is more dangerous than ignorance.&rdquo; &mdash; <footer>George Bernard Shaw</footer></blockquote>',
  },
  {
    q: "It's not what we do once in a while that shapes our lives, but what we do consistently.",
    a: 'Tony Robbins',
    c: '87',
    h: "<blockquote>&ldquo;It's not what we do once in a while that shapes our lives, but what we do consistently.&rdquo; &mdash; <footer>Tony Robbins</footer></blockquote>",
  },
  {
    q: 'I live by letting things happen.',
    a: 'Dogen',
    c: '32',
    h: '<blockquote>&ldquo;I live by letting things happen.&rdquo; &mdash; <footer>Dogen</footer></blockquote>',
  },
  {
    q: 'Dream big. Start small. But most of all, start.',
    a: 'Simon Sinek',
    c: '47',
    h: '<blockquote>&ldquo;Dream big. Start small. But most of all, start.&rdquo; &mdash; <footer>Simon Sinek</footer></blockquote>',
  },
  {
    q: 'Nothing endures but change.',
    a: 'Heraclitus',
    c: '27',
    h: '<blockquote>&ldquo;Nothing endures but change.&rdquo; &mdash; <footer>Heraclitus</footer></blockquote>',
  },
  {
    q: 'We run to win, not just to be in the race.  ',
    a: 'Vince Lombardi',
    c: '44',
    h: '<blockquote>&ldquo;We run to win, not just to be in the race.  &rdquo; &mdash; <footer>Vince Lombardi</footer></blockquote>',
  },
  {
    q: 'Realistic people do not accomplish extraordinary things.',
    a: 'John Eliot',
    c: '56',
    h: '<blockquote>&ldquo;Realistic people do not accomplish extraordinary things.&rdquo; &mdash; <footer>John Eliot</footer></blockquote>',
  },
  {
    q: 'I learned the value of hard work by working hard. ',
    a: 'Margaret Mead',
    c: '50',
    h: '<blockquote>&ldquo;I learned the value of hard work by working hard. &rdquo; &mdash; <footer>Margaret Mead</footer></blockquote>',
  },
  {
    q: 'My powers are ordinary. Only my application brings me success.',
    a: 'Isaac Newton',
    c: '62',
    h: '<blockquote>&ldquo;My powers are ordinary. Only my application brings me success.&rdquo; &mdash; <footer>Isaac Newton</footer></blockquote>',
  },
  {
    q: 'Positive thinking can be contagious. Being surrounded by winners helps you develop into a winner.',
    a: 'Arnold Schwarzenegger',
    c: '97',
    h: '<blockquote>&ldquo;Positive thinking can be contagious. Being surrounded by winners helps you develop into a winner.&rdquo; &mdash; <footer>Arnold Schwarzenegger</footer></blockquote>',
  },
  {
    q: "Until you change how you get things done, you'll never know what works best.",
    a: 'Roy T. Bennett',
    c: '76',
    h: "<blockquote>&ldquo;Until you change how you get things done, you'll never know what works best.&rdquo; &mdash; <footer>Roy T. Bennett</footer></blockquote>",
  },
  {
    q: 'Do not fear failure but rather fear not trying.',
    a: 'Roy T. Bennett',
    c: '47',
    h: '<blockquote>&ldquo;Do not fear failure but rather fear not trying.&rdquo; &mdash; <footer>Roy T. Bennett</footer></blockquote>',
  },
  {
    q: "You can never get enough of what you don't need to make you happy.",
    a: 'Eric Hoffer',
    c: '66',
    h: "<blockquote>&ldquo;You can never get enough of what you don't need to make you happy.&rdquo; &mdash; <footer>Eric Hoffer</footer></blockquote>",
  },
  {
    q: 'The measure of who we are is what we do with what we have.',
    a: 'Vince Lombardi',
    c: '58',
    h: '<blockquote>&ldquo;The measure of who we are is what we do with what we have.&rdquo; &mdash; <footer>Vince Lombardi</footer></blockquote>',
  },
  {
    q: 'Few things are more deceptive than memories.',
    a: 'Carlos Ruiz Zafon',
    c: '44',
    h: '<blockquote>&ldquo;Few things are more deceptive than memories.&rdquo; &mdash; <footer>Carlos Ruiz Zafon</footer></blockquote>',
  },
  {
    q: "Don't be afraid to go slowly. Be afraid of stopping.",
    a: 'Zen Proverb',
    c: '52',
    h: "<blockquote>&ldquo;Don't be afraid to go slowly. Be afraid of stopping.&rdquo; &mdash; <footer>Zen Proverb</footer></blockquote>",
  },
  {
    q: 'Anyone who has ever made anything of importance was disciplined.',
    a: 'Andrew Hendrixson',
    c: '64',
    h: '<blockquote>&ldquo;Anyone who has ever made anything of importance was disciplined.&rdquo; &mdash; <footer>Andrew Hendrixson</footer></blockquote>',
  },
  {
    q: "The highest form of ignorance is when you reject something you don't know anything about. ",
    a: 'Wayne Dyer',
    c: '90',
    h: "<blockquote>&ldquo;The highest form of ignorance is when you reject something you don't know anything about. &rdquo; &mdash; <footer>Wayne Dyer</footer></blockquote>",
  },
  {
    q: "A zen master's life is one continuous mistake.",
    a: 'Dogen',
    c: '46',
    h: "<blockquote>&ldquo;A zen master's life is one continuous mistake.&rdquo; &mdash; <footer>Dogen</footer></blockquote>",
  },
  {
    q: 'Throw me to the wolves and I will return leading the pack.  ',
    a: 'Seneca',
    c: '60',
    h: '<blockquote>&ldquo;Throw me to the wolves and I will return leading the pack.  &rdquo; &mdash; <footer>Seneca</footer></blockquote>',
  },
  {
    q: 'Convinced myself, I seek not to convince.',
    a: 'Edgar Allan Poe',
    c: '41',
    h: '<blockquote>&ldquo;Convinced myself, I seek not to convince.&rdquo; &mdash; <footer>Edgar Allan Poe</footer></blockquote>',
  },
  {
    q: 'Only by attracting the best people will you accomplish great deeds.',
    a: 'Colin Powell',
    c: '67',
    h: '<blockquote>&ldquo;Only by attracting the best people will you accomplish great deeds.&rdquo; &mdash; <footer>Colin Powell</footer></blockquote>',
  },
  {
    q: 'Life is much more successfully looked at from a single window.',
    a: 'F. Scott Fitzgerald',
    c: '62',
    h: '<blockquote>&ldquo;Life is much more successfully looked at from a single window.&rdquo; &mdash; <footer>F. Scott Fitzgerald</footer></blockquote>',
  },
  {
    q: 'Every failure brings with it the seed of an equivalent success.',
    a: 'Napoleon Hill',
    c: '63',
    h: '<blockquote>&ldquo;Every failure brings with it the seed of an equivalent success.&rdquo; &mdash; <footer>Napoleon Hill</footer></blockquote>',
  },
];
